# Generated by Django 2.2.4 on 2019-08-14 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20190814_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b550d5e-457d-4ede-808b-4a1e431723a0'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
